# Workflow for running nightly calendar updates and thus triggering a new build of the Astro site.
#
name: Update calendar data

on:
  # Runs at 03:00 and 13:00 UTC every day
  schedule:
    - cron: "0 3,13 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  id-token: write

env:
  BUILD_PATH: "${{ github.workspace }}/processing"
  ASTROSITE_PATH: "${{ github.workspace }}/astrosite"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        id: detect-package-manager
        working-directory: ${{ env.BUILD_PATH }}
        run: |
          echo "BUILD_PATH is '${{ env.BUILD_PATH }}'"
          echo "ASTROSITE_PATH is '${{ env.ASTROSITE_PATH }}'"
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager - defaulting to NPM..."
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
            exit 0
          fi
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile }}
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: ${{ env.BUILD_PATH }}
      - name: Run script
        run: |
          npx tsx src/workflows/nightly-batch.ts
        working-directory: ${{ env.BUILD_PATH }}
      - name: Commit changes
        run: |
          scripts/commit-changes.sh
        working-directory: ${{ env.BUILD_PATH }}
        env:
          GIT_AUTHOR_NAME: nightly-batch.yml
          GIT_AUTHOR_EMAIL: lasse.koskela@gmail.com
          GIT_COMMITTER_NAME: nightly-batch.yml
          GIT_COMMITTER_EMAIL: lasse.koskela@gmail.com
